set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_CMAKE_CONFIGURE_OPTIONS $ENV{TRIPLET_VCPKG_CMAKE_CONFIGURE_OPTIONS})
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE $ENV{TRIPLET_VCPKG_CHAINLOAD_TOOLCHAIN_FILE})

message("vcpkg triple set VCPKG_CHAINLOAD_TOOLCHAIN_FILE to $ENV{TRIPLET_VCPKG_CHAINLOAD_TOOLCHAIN_FILE}")
